### ISSUE TITLE
naming inconsistency

### ISSUE THREAD

**Issue by stolarczyk** [maureencarey/metaboLITE_manuscript#1]
https://github.com/maureencarey/metaboLITE_manuscript/blob/c63b8fddc361c9f8f10d65a3bd03e4480e8a18ba/metabolite_manuscript.Rmd#L32

there's inconsistency in the name of the app: `metaboLITE` and `MetaboLITE`. I'm ok with either one, but changing to `metaboLITE` will save some work as that's how I call it everywhere.

**Comment by maureencarey** [comment]
got it - switching to metaboLITE
